version: '3'

services:
  caddy:
    image: caddy:2.3.0
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/etc/caddy
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped